create table if not exists public.review_likes (
  review_id uuid not null references public.reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table if not exists public.review_saves (
  review_id uuid not null references public.reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (review_id, user_id)
);

create table if not exists public.review_comments (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.reviews(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  parent_id uuid references public.review_comments(id) on delete cascade,
  body text not null,
  status text not null default 'visible' check (status in ('visible', 'removed')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

alter table public.review_comments drop constraint if exists review_comments_body_check;
alter table public.review_comments add constraint review_comments_body_check
  check ((status = 'visible' and char_length(trim(body)) between 1 and 500) or (status = 'removed' and body = ''));

create table if not exists public.review_reports (
  id uuid primary key default gen_random_uuid(),
  review_id uuid not null references public.reviews(id) on delete cascade,
  reporter_user_id uuid not null references auth.users(id) on delete cascade,
  reason text not null check (reason in ('spoiler', 'harassment', 'personal_info', 'copyright', 'other')),
  detail text not null default '' check (char_length(detail) <= 500),
  status text not null default 'open' check (status in ('open', 'dismissed', 'actioned')),
  resolved_by uuid references auth.users(id) on delete set null,
  resolved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (review_id, reporter_user_id)
);

create table if not exists public.product_events (
  id bigint generated by default as identity primary key,
  session_id uuid not null,
  event_name text not null check (event_name in ('public_review_view', 'movie_detail_open', 'review_like', 'review_save', 'comment_create', 'report_submit', 'record_start')),
  entity_type text not null check (entity_type in ('review', 'movie', 'record')),
  entity_id uuid,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists review_likes_created_idx on public.review_likes(created_at desc);
create index if not exists review_saves_user_created_idx on public.review_saves(user_id, created_at desc);
create index if not exists review_comments_review_created_idx on public.review_comments(review_id, created_at asc);
create index if not exists review_reports_status_created_idx on public.review_reports(status, created_at asc);
create index if not exists product_events_session_created_idx on public.product_events(session_id, created_at desc);
create index if not exists product_events_name_created_idx on public.product_events(event_name, created_at desc);

alter table public.review_likes enable row level security;
alter table public.review_saves enable row level security;
alter table public.review_comments enable row level security;
alter table public.review_reports enable row level security;
alter table public.product_events enable row level security;

revoke all on public.review_likes from anon, authenticated;
revoke all on public.review_saves from anon, authenticated;
revoke all on public.review_comments from anon, authenticated;
revoke all on public.review_reports from anon, authenticated;
revoke all on public.product_events from anon, authenticated;

create or replace function public.is_public_completed_review(p_review_id uuid)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.reviews
    where id = p_review_id and visibility = 'public' and status = 'completed'
  );
$$;

create or replace function public.list_public_reviews(
  p_mode text default null,
  p_cursor timestamptz default null,
  p_limit integer default 20
)
returns table (
  review_id uuid,
  author_display_name text,
  movie_id uuid,
  movie_title text,
  poster_path text,
  mode text,
  watched_at date,
  rating numeric,
  one_line text,
  body_excerpt text,
  spoiler boolean,
  updated_at timestamptz,
  like_count bigint,
  comment_count bigint,
  save_count bigint,
  viewer_liked boolean,
  viewer_saved boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if p_mode is not null and p_mode not in ('light', 'core') then raise exception 'invalid_mode'; end if;

  return query
  select reviews.id,
         coalesce(nullif(trim(profiles.display_name), ''), 'FLICK 사용자'),
         movies.id,
         movies.title,
         movies.poster_path,
         reviews.mode,
         reviews.watched_at,
         reviews.rating,
         reviews.one_line,
         case when reviews.spoiler then '' else left(reviews.body, 280) end,
         reviews.spoiler,
         reviews.updated_at,
         (select count(*) from public.review_likes likes where likes.review_id = reviews.id),
         (select count(*) from public.review_comments comments where comments.review_id = reviews.id and comments.status = 'visible'),
         (select count(*) from public.review_saves saves where saves.review_id = reviews.id),
         exists (select 1 from public.review_likes likes where likes.review_id = reviews.id and likes.user_id = auth.uid()),
         exists (select 1 from public.review_saves saves where saves.review_id = reviews.id and saves.user_id = auth.uid())
  from public.reviews reviews
  join public.movies movies on movies.id = reviews.movie_id
  left join public.profiles profiles on profiles.id = reviews.user_id
  where reviews.visibility = 'public'
    and reviews.status = 'completed'
    and (p_mode is null or reviews.mode = p_mode)
    and (p_cursor is null or reviews.updated_at < p_cursor)
  order by reviews.updated_at desc, reviews.id desc
  limit least(greatest(coalesce(p_limit, 20), 1), 50);
end;
$$;

create or replace function public.get_review_community(p_review_id uuid)
returns table (
  like_count bigint,
  comment_count bigint,
  save_count bigint,
  viewer_liked boolean,
  viewer_saved boolean,
  can_report boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;

  return query
  select (select count(*) from public.review_likes where review_id = p_review_id),
         (select count(*) from public.review_comments where review_id = p_review_id and status = 'visible'),
         (select count(*) from public.review_saves where review_id = p_review_id),
         exists (select 1 from public.review_likes where review_id = p_review_id and user_id = auth.uid()),
         exists (select 1 from public.review_saves where review_id = p_review_id and user_id = auth.uid()),
         not exists (select 1 from public.reviews where id = p_review_id and user_id = auth.uid());
end;
$$;

create or replace function public.list_review_comments(p_review_id uuid)
returns table (
  comment_id uuid,
  parent_id uuid,
  author_display_name text,
  body text,
  status text,
  created_at timestamptz,
  is_mine boolean
)
language plpgsql
stable
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;

  return query
  select comments.id,
         comments.parent_id,
         coalesce(nullif(trim(profiles.display_name), ''), 'FLICK 사용자'),
         case when comments.status = 'removed' then '' else comments.body end,
         comments.status,
         comments.created_at,
         comments.user_id = auth.uid()
  from public.review_comments comments
  left join public.profiles profiles on profiles.id = comments.user_id
  where comments.review_id = p_review_id
  order by comments.created_at asc;
end;
$$;

create or replace function public.set_review_like(p_review_id uuid, p_active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;
  if coalesce(p_active, false) then
    insert into public.review_likes (review_id, user_id) values (p_review_id, auth.uid()) on conflict do nothing;
  else
    delete from public.review_likes where review_id = p_review_id and user_id = auth.uid();
  end if;
end;
$$;

create or replace function public.set_review_save(p_review_id uuid, p_active boolean)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;
  if coalesce(p_active, false) then
    insert into public.review_saves (review_id, user_id) values (p_review_id, auth.uid()) on conflict do nothing;
  else
    delete from public.review_saves where review_id = p_review_id and user_id = auth.uid();
  end if;
end;
$$;

create or replace function public.add_review_comment(p_review_id uuid, p_body text, p_parent_id uuid default null)
returns uuid
language plpgsql
security definer
set search_path = public
as $$
declare
  v_comment_id uuid;
  v_parent_review_id uuid;
  v_parent_parent_id uuid;
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;
  if char_length(trim(coalesce(p_body, ''))) not between 1 and 500 then raise exception 'invalid_comment'; end if;

  if p_parent_id is not null then
    select review_id, parent_id into v_parent_review_id, v_parent_parent_id
    from public.review_comments where id = p_parent_id and status = 'visible';
    if v_parent_review_id is distinct from p_review_id then raise exception 'invalid_parent_comment'; end if;
    if v_parent_parent_id is not null then raise exception 'reply_depth_exceeded'; end if;
  end if;

  insert into public.review_comments (review_id, user_id, parent_id, body)
  values (p_review_id, auth.uid(), p_parent_id, trim(p_body))
  returning id into v_comment_id;
  return v_comment_id;
end;
$$;

create or replace function public.remove_review_comment(p_comment_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  update public.review_comments
  set body = '', status = 'removed', updated_at = now()
  where id = p_comment_id and user_id = auth.uid() and status = 'visible';
  if not found then raise exception 'comment_not_found'; end if;
end;
$$;

create or replace function public.report_review(p_review_id uuid, p_reason text, p_detail text default '')
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if p_reason not in ('spoiler', 'harassment', 'personal_info', 'copyright', 'other') then raise exception 'invalid_report_reason'; end if;
  if not public.is_public_completed_review(p_review_id) then raise exception 'review_not_found'; end if;
  if exists (select 1 from public.reviews where id = p_review_id and user_id = auth.uid()) then raise exception 'cannot_report_own_review'; end if;

  insert into public.review_reports (review_id, reporter_user_id, reason, detail)
  values (p_review_id, auth.uid(), p_reason, left(trim(coalesce(p_detail, '')), 500))
  on conflict (review_id, reporter_user_id) do update
  set reason = excluded.reason, detail = excluded.detail, status = 'open', resolved_by = null, resolved_at = null, updated_at = now();
end;
$$;

create or replace function public.track_product_event(
  p_session_id uuid,
  p_event_name text,
  p_entity_type text,
  p_entity_id uuid default null,
  p_metadata jsonb default '{}'::jsonb
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_metadata jsonb;
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if p_event_name not in ('public_review_view', 'movie_detail_open', 'review_like', 'review_save', 'comment_create', 'report_submit', 'record_start') then raise exception 'invalid_event_name'; end if;
  if p_entity_type not in ('review', 'movie', 'record') then raise exception 'invalid_entity_type'; end if;

  v_metadata := jsonb_strip_nulls(jsonb_build_object(
    'surface', left(nullif(p_metadata ->> 'surface', ''), 40),
    'mode', left(nullif(p_metadata ->> 'mode', ''), 10),
    'source', left(nullif(p_metadata ->> 'source', ''), 40)
  ));

  insert into public.product_events (session_id, event_name, entity_type, entity_id, metadata)
  values (p_session_id, p_event_name, p_entity_type, p_entity_id, v_metadata);
end;
$$;

create or replace function public.admin_list_review_reports(p_limit integer default 50)
returns table (
  report_id uuid,
  review_id uuid,
  movie_title text,
  author_display_name text,
  reporter_display_name text,
  reason text,
  detail text,
  status text,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = auth.uid() and can_moderate_reviews
  ) then raise exception 'admin_moderate_reviews_required'; end if;

  return query
  select reports.id,
         reports.review_id,
         movies.title,
         coalesce(nullif(trim(authors.display_name), ''), 'FLICK 사용자'),
         coalesce(nullif(trim(reporters.display_name), ''), 'FLICK 사용자'),
         reports.reason,
         reports.detail,
         reports.status,
         reports.created_at
  from public.review_reports reports
  join public.reviews reviews on reviews.id = reports.review_id
  join public.movies movies on movies.id = reviews.movie_id
  left join public.profiles authors on authors.id = reviews.user_id
  left join public.profiles reporters on reporters.id = reports.reporter_user_id
  where reports.status = 'open'
  order by reports.created_at asc
  limit least(greatest(coalesce(p_limit, 50), 1), 100);
end;
$$;

create or replace function public.admin_resolve_review_report(p_report_id uuid, p_action text)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_review_id uuid;
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = auth.uid() and can_moderate_reviews
  ) then raise exception 'admin_moderate_reviews_required'; end if;
  if p_action not in ('dismiss', 'make_private') then raise exception 'invalid_report_action'; end if;

  select review_id into v_review_id from public.review_reports where id = p_report_id and status = 'open' for update;
  if v_review_id is null then raise exception 'report_not_found'; end if;

  if p_action = 'make_private' then
    update public.reviews set visibility = 'private', updated_at = now() where id = v_review_id;
  end if;

  update public.review_reports
  set status = case when p_action = 'make_private' then 'actioned' else 'dismissed' end,
      resolved_by = auth.uid(), resolved_at = now(), updated_at = now()
  where id = p_report_id;

  insert into public.admin_audit_events (admin_user_id, action, target_type, target_id, metadata)
  values (
    auth.uid(),
    case when p_action = 'make_private' then 'review_report_made_private' else 'review_report_dismissed' end,
    'review_report',
    p_report_id::text,
    jsonb_build_object('review_id', v_review_id)
  );
end;
$$;

revoke all on function public.is_public_completed_review(uuid) from public;
revoke all on function public.list_public_reviews(text, timestamptz, integer) from public;
revoke all on function public.get_review_community(uuid) from public;
revoke all on function public.list_review_comments(uuid) from public;
revoke all on function public.set_review_like(uuid, boolean) from public;
revoke all on function public.set_review_save(uuid, boolean) from public;
revoke all on function public.add_review_comment(uuid, text, uuid) from public;
revoke all on function public.remove_review_comment(uuid) from public;
revoke all on function public.report_review(uuid, text, text) from public;
revoke all on function public.track_product_event(uuid, text, text, uuid, jsonb) from public;
revoke all on function public.admin_list_review_reports(integer) from public;
revoke all on function public.admin_resolve_review_report(uuid, text) from public;

grant execute on function public.list_public_reviews(text, timestamptz, integer) to authenticated;
grant execute on function public.get_review_community(uuid) to authenticated;
grant execute on function public.list_review_comments(uuid) to authenticated;
grant execute on function public.set_review_like(uuid, boolean) to authenticated;
grant execute on function public.set_review_save(uuid, boolean) to authenticated;
grant execute on function public.add_review_comment(uuid, text, uuid) to authenticated;
grant execute on function public.remove_review_comment(uuid) to authenticated;
grant execute on function public.report_review(uuid, text, text) to authenticated;
grant execute on function public.track_product_event(uuid, text, text, uuid, jsonb) to authenticated;
grant execute on function public.admin_list_review_reports(integer) to authenticated;
grant execute on function public.admin_resolve_review_report(uuid, text) to authenticated;

comment on table public.review_likes is 'One idempotent like per authenticated user and public completed review.';
comment on table public.review_saves is 'Private saved-review relationship for the owning authenticated user.';
comment on table public.review_comments is 'One-level public review discussion with soft removal to preserve reply context.';
comment on table public.review_reports is 'Deduplicated user reports reviewed by a permission-gated administrator.';
comment on table public.product_events is 'Pseudonymous session events with an allow-listed metadata shape and no email or review body.';

-- Rollback: revoke the Stage 5A RPCs first. Keep user-generated interaction data exported
-- before dropping child tables. The migration does not alter existing review ownership policies.
