create table if not exists public.admin_access (
  user_id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'super_admin' check (role in ('super_admin')),
  can_view_users boolean not null default true,
  can_view_reviews boolean not null default true,
  can_moderate_reviews boolean not null default false,
  can_delete_reviews boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_events (
  id bigint generated by default as identity primary key,
  admin_user_id uuid not null references auth.users(id) on delete restrict,
  action text not null,
  target_type text not null,
  target_id text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index if not exists admin_audit_events_created_idx
  on public.admin_audit_events(created_at desc);

alter table public.admin_access enable row level security;
alter table public.admin_audit_events enable row level security;

revoke all on public.admin_access from anon, authenticated;
revoke all on public.admin_audit_events from anon, authenticated;

create or replace function public.admin_my_access()
returns table (
  role text,
  can_view_users boolean,
  can_view_reviews boolean,
  can_moderate_reviews boolean,
  can_delete_reviews boolean
)
language sql
stable
security definer
set search_path = public
as $$
  select access.role,
         access.can_view_users,
         access.can_view_reviews,
         access.can_moderate_reviews,
         access.can_delete_reviews
  from public.admin_access access
  where access.user_id = auth.uid();
$$;

create or replace function public.admin_set_my_permissions(
  p_can_view_users boolean,
  p_can_view_reviews boolean,
  p_can_moderate_reviews boolean,
  p_can_delete_reviews boolean
)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = v_user_id and role = 'super_admin'
  ) then
    raise exception 'admin_required';
  end if;

  update public.admin_access
  set can_view_users = coalesce(p_can_view_users, false),
      can_view_reviews = coalesce(p_can_view_reviews, false),
      can_moderate_reviews = coalesce(p_can_moderate_reviews, false),
      can_delete_reviews = coalesce(p_can_delete_reviews, false),
      updated_at = now()
  where user_id = v_user_id;

  insert into public.admin_audit_events (admin_user_id, action, target_type, target_id, metadata)
  values (
    v_user_id,
    'permissions_updated',
    'admin_access',
    v_user_id::text,
    jsonb_build_object(
      'can_view_users', coalesce(p_can_view_users, false),
      'can_view_reviews', coalesce(p_can_view_reviews, false),
      'can_moderate_reviews', coalesce(p_can_moderate_reviews, false),
      'can_delete_reviews', coalesce(p_can_delete_reviews, false)
    )
  );
end;
$$;

create or replace function public.admin_list_users(p_limit integer default 100)
returns table (
  user_id uuid,
  email text,
  display_name text,
  created_at timestamptz,
  last_sign_in_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if not exists (
    select 1 from public.admin_access
    where admin_access.user_id = v_user_id and can_view_users
  ) then
    raise exception 'admin_view_users_required';
  end if;

  insert into public.admin_audit_events (admin_user_id, action, target_type, metadata)
  values (v_user_id, 'users_viewed', 'user', jsonb_build_object('limit', least(greatest(coalesce(p_limit, 100), 1), 200)));

  return query
  select users.id,
         users.email::text,
         profiles.display_name,
         users.created_at,
         users.last_sign_in_at
  from auth.users users
  left join public.profiles profiles on profiles.id = users.id
  order by users.created_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 200);
end;
$$;

create or replace function public.admin_list_reviews(p_limit integer default 100)
returns table (
  review_id uuid,
  owner_user_id uuid,
  owner_email text,
  owner_display_name text,
  movie_title text,
  mode text,
  status text,
  visibility text,
  rating numeric,
  one_line text,
  body_preview text,
  updated_at timestamptz
)
language plpgsql
security definer
set search_path = public, auth
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if not exists (
    select 1 from public.admin_access
    where admin_access.user_id = v_user_id and can_view_reviews
  ) then
    raise exception 'admin_view_reviews_required';
  end if;

  insert into public.admin_audit_events (admin_user_id, action, target_type, metadata)
  values (v_user_id, 'reviews_viewed', 'review', jsonb_build_object('limit', least(greatest(coalesce(p_limit, 100), 1), 200)));

  return query
  select reviews.id,
         reviews.user_id,
         users.email::text,
         profiles.display_name,
         movies.title,
         reviews.mode,
         reviews.status,
         reviews.visibility,
         reviews.rating,
         reviews.one_line,
         left(reviews.body, 500),
         reviews.updated_at
  from public.reviews reviews
  join public.movies movies on movies.id = reviews.movie_id
  join auth.users users on users.id = reviews.user_id
  left join public.profiles profiles on profiles.id = reviews.user_id
  order by reviews.updated_at desc
  limit least(greatest(coalesce(p_limit, 100), 1), 200);
end;
$$;

create or replace function public.admin_make_review_private(p_review_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_owner_id uuid;
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = v_user_id and can_moderate_reviews
  ) then
    raise exception 'admin_moderate_reviews_required';
  end if;

  update public.reviews
  set visibility = 'private', updated_at = now()
  where id = p_review_id
  returning user_id into v_owner_id;

  if v_owner_id is null then raise exception 'review_not_found'; end if;

  insert into public.admin_audit_events (admin_user_id, action, target_type, target_id, metadata)
  values (v_user_id, 'review_made_private', 'review', p_review_id::text, jsonb_build_object('owner_user_id', v_owner_id));
end;
$$;

create or replace function public.admin_delete_review(p_review_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
  v_owner_id uuid;
  v_movie_id uuid;
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = v_user_id and can_delete_reviews
  ) then
    raise exception 'admin_delete_reviews_required';
  end if;

  select user_id, movie_id into v_owner_id, v_movie_id
  from public.reviews where id = p_review_id for update;
  if v_owner_id is null then raise exception 'review_not_found'; end if;

  delete from public.reviews where id = p_review_id;

  insert into public.admin_audit_events (admin_user_id, action, target_type, target_id, metadata)
  values (
    v_user_id,
    'review_deleted',
    'review',
    p_review_id::text,
    jsonb_build_object('owner_user_id', v_owner_id, 'movie_id', v_movie_id)
  );
end;
$$;

create or replace function public.admin_list_audit_events(p_limit integer default 30)
returns table (
  event_id bigint,
  action text,
  target_type text,
  target_id text,
  metadata jsonb,
  created_at timestamptz
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id uuid := auth.uid();
begin
  if not exists (
    select 1 from public.admin_access
    where user_id = v_user_id and role = 'super_admin'
  ) then
    raise exception 'admin_required';
  end if;

  return query
  select events.id, events.action, events.target_type, events.target_id, events.metadata, events.created_at
  from public.admin_audit_events events
  order by events.created_at desc
  limit least(greatest(coalesce(p_limit, 30), 1), 100);
end;
$$;

revoke all on function public.admin_my_access() from public;
revoke all on function public.admin_set_my_permissions(boolean, boolean, boolean, boolean) from public;
revoke all on function public.admin_list_users(integer) from public;
revoke all on function public.admin_list_reviews(integer) from public;
revoke all on function public.admin_make_review_private(uuid) from public;
revoke all on function public.admin_delete_review(uuid) from public;
revoke all on function public.admin_list_audit_events(integer) from public;

grant execute on function public.admin_my_access() to authenticated;
grant execute on function public.admin_set_my_permissions(boolean, boolean, boolean, boolean) to authenticated;
grant execute on function public.admin_list_users(integer) to authenticated;
grant execute on function public.admin_list_reviews(integer) to authenticated;
grant execute on function public.admin_make_review_private(uuid) to authenticated;
grant execute on function public.admin_delete_review(uuid) to authenticated;
grant execute on function public.admin_list_audit_events(integer) to authenticated;

comment on table public.admin_access is
  'Server-authorized admin membership and independently switchable operational permissions.';
comment on table public.admin_audit_events is
  'Append-only metadata audit trail for admin views, permission changes, moderation, and deletion.';

-- Bootstrap super admins outside source control by resolving an existing auth user
-- in the production dashboard. Never commit a personal admin email to this migration.
